"""empty message

Revision ID: 1dba3ca24007
Revises: 6417a5caa3f1
Create Date: 2018-04-22 19:39:00.941190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dba3ca24007'
down_revision = '6417a5caa3f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ngrok', sa.Column('loc', sa.String(length=128), nullable=True))
    op.add_column('ngrok', sa.Column('pub', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_ngrok_pub'), 'ngrok', ['pub'], unique=True)
    op.drop_index('ix_ngrok_url', table_name='ngrok')
    op.drop_column('ngrok', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ngrok', sa.Column('url', sa.VARCHAR(length=128), nullable=True))
    op.create_index('ix_ngrok_url', 'ngrok', ['url'], unique=1)
    op.drop_index(op.f('ix_ngrok_pub'), table_name='ngrok')
    op.drop_column('ngrok', 'pub')
    op.drop_column('ngrok', 'loc')
    # ### end Alembic commands ###
