"""tasks

Revision ID: 1f77008a0f46
Revises: ab34e5134e45
Create Date: 2018-06-20 00:05:17.458908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f77008a0f46'
down_revision = 'ab34e5134e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ngrok', sa.Column('complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ngrok', 'complete')
    # ### end Alembic commands ###
