"""empty message

Revision ID: 6417a5caa3f1
Revises: 
Create Date: 2018-04-15 17:07:00.724350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6417a5caa3f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ngrok',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('time', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ngrok_time'), 'ngrok', ['time'], unique=True)
    op.create_index(op.f('ix_ngrok_url'), 'ngrok', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ngrok_url'), table_name='ngrok')
    op.drop_index(op.f('ix_ngrok_time'), table_name='ngrok')
    op.drop_table('ngrok')
    # ### end Alembic commands ###
